FusedOnlineAttention8x8BF16FpgaSafePackerExpLutDebug:
    agfi: agfi-0af396794e7c1fe5e
    deploy_quintuplet_override: null
    custom_runtime_config: null

FusedOnlineAttention8x8BF16FpgaSafePackerExpLut:
    # agfi: agfi-04498a15b23a53ebd
    # agfi: agfi-0d8086ddbf0f73961
    agfi: agfi-0944de976804a416c
    deploy_quintuplet_override: null
    custom_runtime_config: null

FusedOnlineAttention8x8BF16FpgaSafePacker:
    agfi: agfi-0f1cfdb84cd8645f6 #agfi-0a318237625aef929 #agfi-01ebbc26d6edf3b03 #agfi-01295220b7d1b16a6
    deploy_quintuplet_override: null
    custom_runtime_config: null

FusedOnlineAttention8x8BF16FpgaSafe:
    agfi: agfi-024e15ac13530f616 #agfi-07d829c020e2817ea #agfi-058cab5290743b6fe
    deploy_quintuplet_override: null
    custom_runtime_config: null

FusedMatmulSoftmax8x8BF16FpgaSafe:
    agfi: agfi-0bc1f6c731fa58937
    deploy_quintuplet_override: null
    custom_runtime_config: null

# FusedMatmulSoftmax8x8BF16FpgaSafe:
    # agfi: agfi-05da581ad23d1f165
    # deploy_quintuplet_override: null
    # custom_runtime_config: null

MatmulAccel8x8BF16FpgaSafe:
    agfi: agfi-0e0f1c3e371d223e3
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4BF16FpgaSafe:
    agfi: agfi-07e09223d8aa14138
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16NoAPrefetchDebug:
    # agfi: agfi-028c80eea2f0c1ea1
    agfi: agfi-0fbed46add314a910
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v7_minimal_scratchpad:
    agfi: agfi-0bcd625208f76e9b3
    deploy_quintuplet_override: null
    custom_runtime_config: null

# 20 hz
MatmulAccel4x4WSBF16v6:
    agfi: agfi-093565e5940bf49e5
    deploy_quintuplet_override: null
    custom_runtime_config: null

# 10 hz
MatmulAccel4x4WSBF16v5:
    agfi: agfi-04540d05d225004e0
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v4:
    agfi: agfi-02327d1676b33ad91                     
    deploy_quintuplet_override: null                 
    custom_runtime_config: null

MatmulAccel4x4WSBF16v3:
    agfi: agfi-069f4eb7b1811ea37
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v2:
    agfi: agfi-0c15311269f6abe73
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16:
    agfi: agfi-0eb1594fd4d7a2bfc
    deploy_quintuplet_override: null
    custom_runtime_config: null

SoftmaxAccel128v2:
    agfi: agfi-0dc4b73a6671d7818                                                                          
    deploy_quintuplet_override: null                                                                      
    custom_runtime_config: null                                                                           

SoftmaxAccel128:
    agfi: agfi-0f9e5c3340edbe3aa
    deploy_quintuplet_override: null
    custom_runtime_config: null
