MatmulAccel4x4WSBF16NoAPrefetchDebug:
    agfi: agfi-028c80eea2f0c1ea1
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v7_minimal_scratchpad:
    agfi: agfi-0bcd625208f76e9b3
    deploy_quintuplet_override: null
    custom_runtime_config: null

# 20 hz
MatmulAccel4x4WSBF16v6:
    agfi: agfi-093565e5940bf49e5
    deploy_quintuplet_override: null
    custom_runtime_config: null

# 10 hz
MatmulAccel4x4WSBF16v5:
    agfi: agfi-04540d05d225004e0
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v4:
    agfi: agfi-02327d1676b33ad91                     
    deploy_quintuplet_override: null                 
    custom_runtime_config: null

MatmulAccel4x4WSBF16v3:
    agfi: agfi-069f4eb7b1811ea37
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16v2:
    agfi: agfi-0c15311269f6abe73
    deploy_quintuplet_override: null
    custom_runtime_config: null

MatmulAccel4x4WSBF16:
    agfi: agfi-0eb1594fd4d7a2bfc
    deploy_quintuplet_override: null
    custom_runtime_config: null

SoftmaxAccel128v2:
    agfi: agfi-0dc4b73a6671d7818                                                                          
    deploy_quintuplet_override: null                                                                      
    custom_runtime_config: null                                                                           

SoftmaxAccel128:
    agfi: agfi-0f9e5c3340edbe3aa
    deploy_quintuplet_override: null
    custom_runtime_config: null