# this refers to build farms defined in config_build_farm.yaml                                                                                                                                             [0/1805]
build_farm:
  # managerinit replace start
  base_recipe: build-farm-recipes/externally_provisioned.yaml
  recipe_arg_overrides:
    build_farm_tag: mainbuildfarm
    build_farm_hosts:
      - localhost
    default_build_dir: /home/ubuntu/local_fsim_builds

builds_to_run:
    # this section references builds defined in config_build_recipes.yaml
    # if you add a build here, it will be built when you run buildbitstream
    - GemminiBF16Default8

agfis_to_share:
    - GemminiBF16Default8

share_with_accounts:
    # To share with a specific user:
    somebodysname: 123456789012
    # To share publicly:
    # public: public
