// Generated by CIRCT firtool-1.62.1
// VCS coverage exclude_file
module ram_66x16(
  input  [6:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [15:0] R0_data,
  input  [6:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [15:0] W0_data
);

  reg [15:0] Memory[0:65];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 16'bx;
endmodule

module Queue66_UInt16(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [15:0] io_enq_bits,
  input         io_deq_ready,
  output        io_deq_valid,
  output [15:0] io_deq_bits
);

  reg  [6:0] enq_ptr_value;
  reg  [6:0] deq_ptr_value;
  reg        maybe_full;
  wire       ptr_match = enq_ptr_value == deq_ptr_value;
  wire       empty = ptr_match & ~maybe_full;
  wire       full = ptr_match & maybe_full;
  wire       do_enq = ~full & io_enq_valid;
  wire       do_deq = io_deq_ready & ~empty;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 7'h0;
      deq_ptr_value <= 7'h0;
      maybe_full <= 1'h0;
    end
    else begin
      if (do_enq) begin
        if (enq_ptr_value == 7'h41)
          enq_ptr_value <= 7'h0;
        else
          enq_ptr_value <= enq_ptr_value + 7'h1;
      end
      if (do_deq) begin
        if (deq_ptr_value == 7'h41)
          deq_ptr_value <= 7'h0;
        else
          deq_ptr_value <= deq_ptr_value + 7'h1;
      end
      if (~(do_enq == do_deq))
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_66x16 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
endmodule

module Controller(
  input         clock,
                reset,
                io_cmdValid,
  output        io_cmdReady,
  input  [6:0]  io_k,
  input         io_clearOnStart,
                io_inValid,
  output        io_inReady,
  input  [15:0] io_in_left_0,
                io_in_left_1,
                io_in_top_0,
                io_in_top_1,
  output [15:0] io_out_left_0,
                io_out_left_1,
                io_out_top_0,
                io_out_top_1,
  output        io_outValid,
                io_clear,
                io_busy,
                io_done
);

  wire        _topQ_1_io_enq_ready;
  wire        _topQ_1_io_deq_valid;
  wire [15:0] _topQ_1_io_deq_bits;
  wire        _topQ_0_io_enq_ready;
  wire        _topQ_0_io_deq_valid;
  wire [15:0] _topQ_0_io_deq_bits;
  wire        _leftQ_1_io_enq_ready;
  wire        _leftQ_1_io_deq_valid;
  wire [15:0] _leftQ_1_io_deq_bits;
  wire        _leftQ_0_io_enq_ready;
  wire        _leftQ_0_io_deq_valid;
  wire [15:0] _leftQ_0_io_deq_bits;
  reg  [2:0]  state;
  reg  [6:0]  kReg;
  reg  [6:0]  loadCount;
  reg  [6:0]  tCount;
  reg         clearThisRun;
  wire        canLoad =
    _leftQ_0_io_enq_ready & _leftQ_1_io_enq_ready & _topQ_0_io_enq_ready
    & _topQ_1_io_enq_ready;
  wire        _io_inReady_T = state == 3'h1;
  wire        doLoad = _io_inReady_T & io_inValid & canLoad;
  wire        _GEN = state == 3'h1;
  wire        _GEN_0 = state == 3'h2;
  wire        _GEN_1 = state == 3'h3;
  wire        active = tCount < kReg;
  wire        _GEN_2 = ~(|state) | _GEN | _GEN_0;
  wire [6:0]  _active_T_13 = kReg + 7'h1;
  wire        active_1 = (|tCount) & tCount < _active_T_13;
  wire        active_2 = tCount < kReg;
  wire        active_3 = (|tCount) & tCount < _active_T_13;
  wire [6:0]  _tCount_T = tCount + 7'h1;
  wire        _GEN_3 = _tCount_T >= kReg + 7'h2;
  wire [6:0]  _nextLoadCount_T = loadCount + 7'h1;
  always @(posedge clock) begin
    if (reset) begin
      state <= 3'h0;
      kReg <= 7'h0;
      loadCount <= 7'h0;
      tCount <= 7'h0;
      clearThisRun <= 1'h1;
    end
    else begin
      if (|state) begin
        if (_GEN) begin
          if (doLoad & _nextLoadCount_T == kReg)
            state <= {2'h1, ~clearThisRun};
        end
        else if (_GEN_0) begin
          state <= kReg == 7'h0 ? 3'h4 : 3'h3;
          tCount <= 7'h0;
        end
        else begin
          if (_GEN_1) begin
            if (_GEN_3)
              state <= 3'h4;
          end
          else if (state == 3'h4)
            state <= 3'h0;
          if (~_GEN_1 | _GEN_3) begin
          end
          else
            tCount <= _tCount_T;
        end
        if (_GEN & doLoad)
          loadCount <= _nextLoadCount_T;
      end
      else if (io_cmdValid) begin
        state <= io_k == 7'h0 ? (io_clearOnStart ? 3'h2 : 3'h4) : 3'h1;
        loadCount <= 7'h0;
        tCount <= 7'h0;
      end
      if (~(|state) & io_cmdValid) begin
        kReg <= io_k;
        clearThisRun <= io_clearOnStart;
      end
    end
  end // always @(posedge)
  Queue66_UInt16 leftQ_0 (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_leftQ_0_io_enq_ready),
    .io_enq_valid (doLoad),
    .io_enq_bits  (io_in_left_0),
    .io_deq_ready (~_GEN_2 & _GEN_1 & active),
    .io_deq_valid (_leftQ_0_io_deq_valid),
    .io_deq_bits  (_leftQ_0_io_deq_bits)
  );
  Queue66_UInt16 leftQ_1 (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_leftQ_1_io_enq_ready),
    .io_enq_valid (doLoad),
    .io_enq_bits  (io_in_left_1),
    .io_deq_ready (~_GEN_2 & _GEN_1 & active_1),
    .io_deq_valid (_leftQ_1_io_deq_valid),
    .io_deq_bits  (_leftQ_1_io_deq_bits)
  );
  Queue66_UInt16 topQ_0 (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_topQ_0_io_enq_ready),
    .io_enq_valid (doLoad),
    .io_enq_bits  (io_in_top_0),
    .io_deq_ready (~_GEN_2 & _GEN_1 & active_2),
    .io_deq_valid (_topQ_0_io_deq_valid),
    .io_deq_bits  (_topQ_0_io_deq_bits)
  );
  Queue66_UInt16 topQ_1 (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_topQ_1_io_enq_ready),
    .io_enq_valid (doLoad),
    .io_enq_bits  (io_in_top_1),
    .io_deq_ready (~_GEN_2 & _GEN_1 & active_3),
    .io_deq_valid (_topQ_1_io_deq_valid),
    .io_deq_bits  (_topQ_1_io_deq_bits)
  );
  assign io_cmdReady = ~(|state);
  assign io_inReady = _io_inReady_T & canLoad;
  assign io_out_left_0 =
    _GEN_2 | ~(_GEN_1 & active & _leftQ_0_io_deq_valid) ? 16'h0 : _leftQ_0_io_deq_bits;
  assign io_out_left_1 =
    _GEN_2 | ~(_GEN_1 & active_1 & _leftQ_1_io_deq_valid) ? 16'h0 : _leftQ_1_io_deq_bits;
  assign io_out_top_0 =
    _GEN_2 | ~(_GEN_1 & active_2 & _topQ_0_io_deq_valid) ? 16'h0 : _topQ_0_io_deq_bits;
  assign io_out_top_1 =
    _GEN_2 | ~(_GEN_1 & active_3 & _topQ_1_io_deq_valid) ? 16'h0 : _topQ_1_io_deq_bits;
  assign io_outValid = state == 3'h3 & tCount < kReg;
  assign io_clear = state == 3'h2;
  assign io_busy = |state;
  assign io_done = state == 3'h4;
endmodule

module ProcessingElement(
  input         clock,
                reset,
                io_clear,
                io_inValid,
  output        io_outValid,
  input  [15:0] io_left,
                io_top,
  output [15:0] io_right,
                io_down,
  output [31:0] io_result
);

  reg [31:0] accum;
  reg [15:0] down;
  reg [15:0] right;
  reg        v;
  always @(posedge clock) begin
    if (reset) begin
      accum <= 32'h0;
      down <= 16'h0;
      right <= 16'h0;
      v <= 1'h0;
    end
    else begin
      if (io_clear)
        accum <= 32'h0;
      else if (io_inValid)
        accum <= {16'h0, io_top} * {16'h0, io_left} + accum;
      down <= io_top;
      right <= io_left;
      v <= ~io_clear & io_inValid;
    end
  end // always @(posedge)
  assign io_outValid = v;
  assign io_right = right;
  assign io_down = down;
  assign io_result = accum;
endmodule

module Mesh(
  input         clock,
                reset,
  input  [15:0] io_left_0,
                io_left_1,
                io_top_0,
                io_top_1,
  input         io_inValid,
                io_clear,
  output [31:0] io_out_0_0,
                io_out_0_1,
                io_out_1_0,
                io_out_1_1
);

  wire        _PEs_1_0_io_outValid;
  wire [15:0] _PEs_1_0_io_right;
  wire        _PEs_0_1_io_outValid;
  wire [15:0] _PEs_0_1_io_down;
  wire        _PEs_0_0_io_outValid;
  wire [15:0] _PEs_0_0_io_right;
  wire [15:0] _PEs_0_0_io_down;
  ProcessingElement PEs_0_0 (
    .clock       (clock),
    .reset       (reset),
    .io_clear    (io_clear),
    .io_inValid  (io_inValid),
    .io_outValid (_PEs_0_0_io_outValid),
    .io_left     (io_left_0),
    .io_top      (io_top_0),
    .io_right    (_PEs_0_0_io_right),
    .io_down     (_PEs_0_0_io_down),
    .io_result   (io_out_0_0)
  );
  ProcessingElement PEs_0_1 (
    .clock       (clock),
    .reset       (reset),
    .io_clear    (io_clear),
    .io_inValid  (_PEs_0_0_io_outValid),
    .io_outValid (_PEs_0_1_io_outValid),
    .io_left     (_PEs_0_0_io_right),
    .io_top      (io_top_1),
    .io_right    (/* unused */),
    .io_down     (_PEs_0_1_io_down),
    .io_result   (io_out_0_1)
  );
  ProcessingElement PEs_1_0 (
    .clock       (clock),
    .reset       (reset),
    .io_clear    (io_clear),
    .io_inValid  (_PEs_0_0_io_outValid),
    .io_outValid (_PEs_1_0_io_outValid),
    .io_left     (io_left_1),
    .io_top      (_PEs_0_0_io_down),
    .io_right    (_PEs_1_0_io_right),
    .io_down     (/* unused */),
    .io_result   (io_out_1_0)
  );
  ProcessingElement PEs_1_1 (
    .clock       (clock),
    .reset       (reset),
    .io_clear    (io_clear),
    .io_inValid  (_PEs_1_0_io_outValid & _PEs_0_1_io_outValid),
    .io_outValid (/* unused */),
    .io_left     (_PEs_1_0_io_right),
    .io_top      (_PEs_0_1_io_down),
    .io_right    (/* unused */),
    .io_down     (/* unused */),
    .io_result   (io_out_1_1)
  );
endmodule

module SystolicArrayCore(
  input         clock,
                reset,
                io_cmdValid,
  output        io_cmdReady,
  input  [6:0]  io_k,
  input         io_cmdClear,
                io_inValid,
  output        io_inReady,
  input  [15:0] io_in_left_0,
                io_in_left_1,
                io_in_top_0,
                io_in_top_1,
  output [31:0] io_out_0_0,
                io_out_0_1,
                io_out_1_0,
                io_out_1_1,
  output        io_busy,
                io_done
);

  wire [15:0] _controller_io_out_left_0;
  wire [15:0] _controller_io_out_left_1;
  wire [15:0] _controller_io_out_top_0;
  wire [15:0] _controller_io_out_top_1;
  wire        _controller_io_outValid;
  wire        _controller_io_clear;
  Controller controller (
    .clock           (clock),
    .reset           (reset),
    .io_cmdValid     (io_cmdValid),
    .io_cmdReady     (io_cmdReady),
    .io_k            (io_k),
    .io_clearOnStart (io_cmdClear),
    .io_inValid      (io_inValid),
    .io_inReady      (io_inReady),
    .io_in_left_0    (io_in_left_0),
    .io_in_left_1    (io_in_left_1),
    .io_in_top_0     (io_in_top_0),
    .io_in_top_1     (io_in_top_1),
    .io_out_left_0   (_controller_io_out_left_0),
    .io_out_left_1   (_controller_io_out_left_1),
    .io_out_top_0    (_controller_io_out_top_0),
    .io_out_top_1    (_controller_io_out_top_1),
    .io_outValid     (_controller_io_outValid),
    .io_clear        (_controller_io_clear),
    .io_busy         (io_busy),
    .io_done         (io_done)
  );
  Mesh mesh (
    .clock      (clock),
    .reset      (reset),
    .io_left_0  (_controller_io_out_left_0),
    .io_left_1  (_controller_io_out_left_1),
    .io_top_0   (_controller_io_out_top_0),
    .io_top_1   (_controller_io_out_top_1),
    .io_inValid (_controller_io_outValid),
    .io_clear   (_controller_io_clear),
    .io_out_0_0 (io_out_0_0),
    .io_out_0_1 (io_out_0_1),
    .io_out_1_0 (io_out_1_0),
    .io_out_1_1 (io_out_1_1)
  );
endmodule

module SystolicArrayCore2x2OpenLaneTop(
  input          clock,
                 reset,
                 io_cmdValid,
  output         io_cmdReady,
  input          io_cmdClear,
  input  [6:0]   io_k,
  input          io_inValid,
  output         io_inReady,
  input  [31:0]  io_inLeft,
                 io_inTop,
  output [127:0] io_out,
  output         io_busy,
                 io_done
);

  wire [31:0] _core_io_out_0_0;
  wire [31:0] _core_io_out_0_1;
  wire [31:0] _core_io_out_1_0;
  wire [31:0] _core_io_out_1_1;
  SystolicArrayCore core (
    .clock        (clock),
    .reset        (reset),
    .io_cmdValid  (io_cmdValid),
    .io_cmdReady  (io_cmdReady),
    .io_k         (io_k),
    .io_cmdClear  (io_cmdClear),
    .io_inValid   (io_inValid),
    .io_inReady   (io_inReady),
    .io_in_left_0 (io_inLeft[15:0]),
    .io_in_left_1 (io_inLeft[31:16]),
    .io_in_top_0  (io_inTop[15:0]),
    .io_in_top_1  (io_inTop[31:16]),
    .io_out_0_0   (_core_io_out_0_0),
    .io_out_0_1   (_core_io_out_0_1),
    .io_out_1_0   (_core_io_out_1_0),
    .io_out_1_1   (_core_io_out_1_1),
    .io_busy      (io_busy),
    .io_done      (io_done)
  );
  assign io_out =
    {_core_io_out_1_1, _core_io_out_1_0, _core_io_out_0_1, _core_io_out_0_0};
endmodule

