// Generated by CIRCT firtool-1.62.1
module AddRawFN(
  input         io_a_isNaN,
                io_a_isInf,
                io_a_isZero,
                io_a_sign,
  input  [9:0]  io_a_sExp,
                io_a_sig,
  input         io_b_isNaN,
                io_b_isInf,
                io_b_isZero,
                io_b_sign,
  input  [9:0]  io_b_sExp,
                io_b_sig,
  output        io_invalidExc,
                io_rawOut_isNaN,
                io_rawOut_isInf,
                io_rawOut_isZero,
                io_rawOut_sign,
  output [9:0]  io_rawOut_sExp,
  output [11:0] io_rawOut_sig
);

  wire        eqSigns = io_a_sign == ~io_b_sign;
  wire [9:0]  _sDiffExps_T = io_a_sExp - io_b_sExp;
  wire        _common_sExpOut_T = $signed(_sDiffExps_T) < 10'sh0;
  wire [3:0]  _modNatAlignDist_T_4 =
    _common_sExpOut_T ? io_b_sExp[3:0] - io_a_sExp[3:0] : _sDiffExps_T[3:0];
  wire        isMaxAlign =
    (|(_sDiffExps_T[9:4])) & (_sDiffExps_T[9:4] != 6'h3F | _sDiffExps_T[3:0] == 4'h0);
  wire [3:0]  alignDist = isMaxAlign ? 4'hF : _modNatAlignDist_T_4;
  wire        closeSubMags = ~eqSigns & ~isMaxAlign & _modNatAlignDist_T_4 < 4'h2;
  wire        _close_alignedSigA_T_5 = $signed(_sDiffExps_T) > -10'sh1;
  wire [11:0] _close_alignedSigA_T_4 =
    _close_alignedSigA_T_5 & _sDiffExps_T[0] ? {io_a_sig, 2'h0} : 12'h0;
  wire [10:0] _GEN =
    _close_alignedSigA_T_4[10:0]
    | (_close_alignedSigA_T_5 & ~(_sDiffExps_T[0]) ? {io_a_sig, 1'h0} : 11'h0);
  wire [11:0] _close_sSigSum_T_3 =
    {_close_alignedSigA_T_4[11],
     _GEN[10],
     _GEN[9:0] | (_common_sExpOut_T ? io_a_sig : 10'h0)} - {io_b_sig[9], io_b_sig, 1'h0};
  wire        _close_notTotalCancellation_signOut_T =
    $signed(_close_sSigSum_T_3) < 12'sh0;
  wire [10:0] _close_sigSum_T_4 =
    _close_notTotalCancellation_signOut_T
      ? 11'h0 - _close_sSigSum_T_3[10:0]
      : _close_sSigSum_T_3[10:0];
  wire [2:0]  close_normDistReduced2 =
    (|(_close_sigSum_T_4[10:9]))
      ? 3'h0
      : (|(_close_sigSum_T_4[8:7]))
          ? 3'h1
          : (|(_close_sigSum_T_4[6:5]))
              ? 3'h2
              : (|(_close_sigSum_T_4[4:3]))
                  ? 3'h3
                  : {2'h2, _close_sigSum_T_4[2:1] == 2'h0};
  wire [25:0] _close_sigOut_T =
    {15'h0, _close_sigSum_T_4} << {22'h0, close_normDistReduced2, 1'h0};
  wire [8:0]  _far_sigSmaller_T_1 = _common_sExpOut_T ? io_a_sig[8:0] : io_b_sig[8:0];
  wire [13:0] far_mainAlignedSigSmaller = {_far_sigSmaller_T_1, 5'h0} >> alignDist;
  wire [4:0]  far_roundExtraMask_shift = $signed(5'sh10 >>> alignDist[3:2]);
  wire        _far_alignedSigSmaller_T_5 =
    (|(far_mainAlignedSigSmaller[2:0]))
    | (|({|(_far_sigSmaller_T_1[8:6]),
          |(_far_sigSmaller_T_1[5:2]),
          |(_far_sigSmaller_T_1[1:0])}
         & {far_roundExtraMask_shift[1],
            far_roundExtraMask_shift[2],
            far_roundExtraMask_shift[3]}));
  wire [12:0] _far_sigSum_T_3 =
    {1'h0, _common_sExpOut_T ? io_b_sig[8:0] : io_a_sig[8:0], 3'h0}
    + (eqSigns
         ? {1'h0, far_mainAlignedSigSmaller[13:3], _far_alignedSigSmaller_T_5}
         : {1'h1, ~{far_mainAlignedSigSmaller[13:3], _far_alignedSigSmaller_T_5}})
    + {12'h0, ~eqSigns};
  wire        notNaN_isInfOut = io_a_isInf | io_b_isInf;
  wire        addZeros = io_a_isZero & io_b_isZero;
  wire        notNaN_specialCase = notNaN_isInfOut | addZeros;
  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[7]) | io_b_isNaN & ~(io_b_sig[7]) | io_a_isInf & io_b_isInf
    & ~eqSigns;
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;
  assign io_rawOut_isInf = notNaN_isInfOut;
  assign io_rawOut_isZero =
    addZeros | ~notNaN_isInfOut & closeSubMags & ~(|(_close_sigOut_T[10:9]));
  assign io_rawOut_sign =
    eqSigns & io_a_sign | io_a_isInf & io_a_sign | io_b_isInf & ~io_b_sign
    | ~notNaN_specialCase & closeSubMags & (|(_close_sigOut_T[10:9]))
    & (io_a_sign ^ _close_notTotalCancellation_signOut_T) | ~notNaN_specialCase
    & ~closeSubMags & (_common_sExpOut_T ? ~io_b_sign : io_a_sign);
  assign io_rawOut_sExp =
    (closeSubMags | _common_sExpOut_T ? io_b_sExp : io_a_sExp)
    - {6'h0, closeSubMags ? {close_normDistReduced2, 1'h0} : {3'h0, ~eqSigns}};
  assign io_rawOut_sig =
    closeSubMags
      ? {_close_sigOut_T[10:0], 1'h0}
      : eqSigns
          ? {_far_sigSum_T_3[12:2], _far_sigSum_T_3[1] | _far_sigSum_T_3[0]}
          : _far_sigSum_T_3[11:0];
endmodule

module RoundAnyRawFNToRecFN_ie8_is11_oe8_os9(
  input         io_invalidExc,
                io_in_isNaN,
                io_in_isInf,
                io_in_isZero,
                io_in_sign,
  input  [9:0]  io_in_sExp,
  input  [11:0] io_in_sig,
  output [17:0] io_out
);

  wire [8:0]  _roundMask_T_1 = ~(io_in_sExp[8:0]);
  wire [64:0] _GEN = {59'h0, _roundMask_T_1[5:0]};
  wire [64:0] roundMask_shift = $signed(65'sh10000000000000000 >>> _GEN);
  wire [64:0] roundMask_shift_1 = $signed(65'sh10000000000000000 >>> _GEN);
  wire [9:0]  _roundMask_T_34 =
    _roundMask_T_1[8]
      ? (_roundMask_T_1[7]
           ? {~(_roundMask_T_1[6]
                  ? 7'h0
                  : ~{roundMask_shift[57],
                      roundMask_shift[58],
                      roundMask_shift[59],
                      roundMask_shift[60],
                      roundMask_shift[61],
                      roundMask_shift[62],
                      roundMask_shift[63]}),
              3'h7}
           : {7'h0,
              _roundMask_T_1[6]
                ? {roundMask_shift_1[0], roundMask_shift_1[1], roundMask_shift_1[2]}
                : 3'h0})
      : 10'h0;
  wire        _GEN_0 = _roundMask_T_34[0] | io_in_sig[11];
  wire [10:0] _GEN_1 = {_roundMask_T_34[9:1], _GEN_0, 1'h1};
  wire [10:0] _roundPosBit_T =
    io_in_sig[11:1] & {1'h1, ~(_roundMask_T_34[9:1]), ~_GEN_0} & _GEN_1;
  wire [10:0] roundedSig =
    (|_roundPosBit_T)
      ? {1'h0, io_in_sig[11:2] | {_roundMask_T_34[9:1], _GEN_0}} + 11'h1
        & ~((|_roundPosBit_T) & (io_in_sig[10:0] & _GEN_1) == 11'h0
              ? {_roundMask_T_34[9:1], _GEN_0, 1'h1}
              : 11'h0)
      : {1'h0, io_in_sig[11:2] & {~(_roundMask_T_34[9:1]), ~_GEN_0}};
  wire [10:0] sRoundedExp = {io_in_sExp[9], io_in_sExp} + {9'h0, roundedSig[10:9]};
  wire        common_totalUnderflow = $signed(sRoundedExp) < 11'sh7A;
  wire        isNaNOut = io_invalidExc | io_in_isNaN;
  wire        notNaN_isInfOut =
    io_in_isInf | ~isNaNOut & ~io_in_isInf & ~io_in_isZero
    & $signed(sRoundedExp[10:7]) > 4'sh2;
  assign io_out =
    {~isNaNOut & io_in_sign,
     sRoundedExp[8:0] & ~(io_in_isZero | common_totalUnderflow ? 9'h1C0 : 9'h0)
       & {2'h3, ~notNaN_isInfOut, 6'h3F} | (notNaN_isInfOut ? 9'h180 : 9'h0)
       | (isNaNOut ? 9'h1C0 : 9'h0),
     isNaNOut | io_in_isZero | common_totalUnderflow
       ? {isNaNOut, 7'h0}
       : io_in_sig[11] ? roundedSig[8:1] : roundedSig[7:0]};
endmodule

module RoundRawFNToRecFN_e8_s9(
  input         io_invalidExc,
                io_in_isNaN,
                io_in_isInf,
                io_in_isZero,
                io_in_sign,
  input  [9:0]  io_in_sExp,
  input  [11:0] io_in_sig,
  output [17:0] io_out
);

  RoundAnyRawFNToRecFN_ie8_is11_oe8_os9 roundAnyRawFNToRecFN (
    .io_invalidExc (io_invalidExc),
    .io_in_isNaN   (io_in_isNaN),
    .io_in_isInf   (io_in_isInf),
    .io_in_isZero  (io_in_isZero),
    .io_in_sign    (io_in_sign),
    .io_in_sExp    (io_in_sExp),
    .io_in_sig     (io_in_sig),
    .io_out        (io_out)
  );
endmodule

module AddRecFN(
  input  [17:0] io_a,
                io_b,
  output [17:0] io_out
);

  wire        _addRawFN_io_invalidExc;
  wire        _addRawFN_io_rawOut_isNaN;
  wire        _addRawFN_io_rawOut_isInf;
  wire        _addRawFN_io_rawOut_isZero;
  wire        _addRawFN_io_rawOut_sign;
  wire [9:0]  _addRawFN_io_rawOut_sExp;
  wire [11:0] _addRawFN_io_rawOut_sig;
  AddRawFN addRawFN (
    .io_a_isNaN       ((&(io_a[16:15])) & io_a[14]),
    .io_a_isInf       ((&(io_a[16:15])) & ~(io_a[14])),
    .io_a_isZero      (~(|(io_a[16:14]))),
    .io_a_sign        (io_a[17]),
    .io_a_sExp        ({1'h0, io_a[16:8]}),
    .io_a_sig         ({1'h0, |(io_a[16:14]), io_a[7:0]}),
    .io_b_isNaN       ((&(io_b[16:15])) & io_b[14]),
    .io_b_isInf       ((&(io_b[16:15])) & ~(io_b[14])),
    .io_b_isZero      (~(|(io_b[16:14]))),
    .io_b_sign        (io_b[17]),
    .io_b_sExp        ({1'h0, io_b[16:8]}),
    .io_b_sig         ({1'h0, |(io_b[16:14]), io_b[7:0]}),
    .io_invalidExc    (_addRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_addRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_addRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_addRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_addRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_addRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_addRawFN_io_rawOut_sig)
  );
  RoundRawFNToRecFN_e8_s9 roundRawFNToRecFN (
    .io_invalidExc (_addRawFN_io_invalidExc),
    .io_in_isNaN   (_addRawFN_io_rawOut_isNaN),
    .io_in_isInf   (_addRawFN_io_rawOut_isInf),
    .io_in_isZero  (_addRawFN_io_rawOut_isZero),
    .io_in_sign    (_addRawFN_io_rawOut_sign),
    .io_in_sExp    (_addRawFN_io_rawOut_sExp),
    .io_in_sig     (_addRawFN_io_rawOut_sig),
    .io_out        (io_out)
  );
endmodule

module BFloat16Sub(
  input  [15:0] io_in_1,
                io_in_2,
  output [15:0] io_out
);

  wire [17:0] _subFN_io_out;
  wire        recA_rawIn_isZeroExpIn = io_in_1[14:7] == 8'h0;
  wire [2:0]  recA_rawIn_normDist =
    io_in_1[6]
      ? 3'h0
      : io_in_1[5]
          ? 3'h1
          : io_in_1[4]
              ? 3'h2
              : io_in_1[3]
                  ? 3'h3
                  : io_in_1[2] ? 3'h4 : io_in_1[1] ? 3'h5 : {2'h3, ~(io_in_1[0])};
  wire [14:0] _recA_rawIn_subnormFract_T =
    {7'h0, io_in_1[6:0], 1'h0} << recA_rawIn_normDist;
  wire [8:0]  _recA_rawIn_adjustedExp_T_4 =
    (recA_rawIn_isZeroExpIn ? {6'h3F, ~recA_rawIn_normDist} : {1'h0, io_in_1[14:7]})
    + {7'h20, recA_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _recA_T_1 =
    recA_rawIn_isZeroExpIn & ~(|(io_in_1[6:0])) ? 3'h0 : _recA_rawIn_adjustedExp_T_4[8:6];
  wire        recB_rawIn_isZeroExpIn = io_in_2[14:7] == 8'h0;
  wire [2:0]  recB_rawIn_normDist =
    io_in_2[6]
      ? 3'h0
      : io_in_2[5]
          ? 3'h1
          : io_in_2[4]
              ? 3'h2
              : io_in_2[3]
                  ? 3'h3
                  : io_in_2[2] ? 3'h4 : io_in_2[1] ? 3'h5 : {2'h3, ~(io_in_2[0])};
  wire [14:0] _recB_rawIn_subnormFract_T =
    {7'h0, io_in_2[6:0], 1'h0} << recB_rawIn_normDist;
  wire [8:0]  _recB_rawIn_adjustedExp_T_4 =
    (recB_rawIn_isZeroExpIn ? {6'h3F, ~recB_rawIn_normDist} : {1'h0, io_in_2[14:7]})
    + {7'h20, recB_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _recB_T_1 =
    recB_rawIn_isZeroExpIn & ~(|(io_in_2[6:0])) ? 3'h0 : _recB_rawIn_adjustedExp_T_4[8:6];
  wire        outPadded_rawIn_isInf = (&(_subFN_io_out[16:15])) & ~(_subFN_io_out[14]);
  wire        outPadded_isSubnormal = $signed({1'h0, _subFN_io_out[16:8]}) < 10'sh82;
  wire [8:0]  _outPadded_denormFract_T_1 =
    {1'h0, |(_subFN_io_out[16:14]), _subFN_io_out[7:1]} >> 3'h1 - _subFN_io_out[10:8];
  AddRecFN subFN (
    .io_a
      ({io_in_1[15],
        _recA_T_1[2:1],
        _recA_T_1[0] | (&(_recA_rawIn_adjustedExp_T_4[8:7])) & (|(io_in_1[6:0])),
        _recA_rawIn_adjustedExp_T_4[5:0],
        recA_rawIn_isZeroExpIn ? _recA_rawIn_subnormFract_T[6:0] : io_in_1[6:0],
        1'h0}),
    .io_b
      ({io_in_2[15],
        _recB_T_1[2:1],
        _recB_T_1[0] | (&(_recB_rawIn_adjustedExp_T_4[8:7])) & (|(io_in_2[6:0])),
        _recB_rawIn_adjustedExp_T_4[5:0],
        recB_rawIn_isZeroExpIn ? _recB_rawIn_subnormFract_T[6:0] : io_in_2[6:0],
        1'h0}),
    .io_out (_subFN_io_out)
  );
  assign io_out =
    {_subFN_io_out[17],
     (outPadded_isSubnormal ? 8'h0 : _subFN_io_out[15:8] + 8'h7F)
       | {8{(&(_subFN_io_out[16:15])) & _subFN_io_out[14] | outPadded_rawIn_isInf}},
     outPadded_isSubnormal
       ? _outPadded_denormFract_T_1[7:1]
       : outPadded_rawIn_isInf ? 7'h0 : _subFN_io_out[7:1]};
endmodule

module BFloat16Exp(
  input  [15:0] io_in,
  output [15:0] io_out
);

  wire [24:0] shiftedMantissa =
    {{10'h0, io_in[14:7] == 8'h0 ? 8'h0 : {1'h1, io_in[6:0]}} * 18'h171, 7'h0} >> 8'h85
    - io_in[14:7];
  wire [14:0] signedMantissa = {15{io_in[15]}} ^ shiftedMantissa[23:9];
  wire [9:0]  _GEN = {3'h0, signedMantissa[6:0]};
  wire [20:0] p1 = {4'h0, {7'h0, _GEN + 10'h1A6} * 17'h1C} * {14'h0, signedMantissa[6:0]};
  wire [20:0] p2 =
    {4'h0, {7'h0, _GEN + 10'h116} * 17'h38} * {14'h0, ~(signedMantissa[6:0])};
  assign io_out =
    (&(io_in[14:7])) & io_in[6:0] == 7'h0 & io_in[15]
      ? 16'h0
      : (&(io_in[14:7]))
          ? 16'h7F7F
          : {1'h0,
             signedMantissa[14:7] + 8'h7F,
             signedMantissa[6] ? p1[20:14] : ~(p2[20:14])};
endmodule

module BFloat16ToFixed(
  input  [15:0] io_in,
  output [31:0] io_out
);

  wire [8:0]   _shiftAmt_T_3 = ((|(io_in[14:7])) ? {1'h0, io_in[14:7]} : 9'h1) - 9'h72;
  wire [518:0] _shiftedMag_T_1 = {511'h0, |(io_in[14:7]), io_in[6:0]} << _shiftAmt_T_3;
  wire [8:0]   _shiftedMag_T_6 =
    {1'h0, |(io_in[14:7]), io_in[6:0]} >> 9'h0 - _shiftAmt_T_3;
  wire [31:0]  shiftedMag =
    $signed(_shiftAmt_T_3) > -9'sh1
      ? _shiftedMag_T_1[31:0]
      : {24'h0, _shiftedMag_T_6[7:0]};
  assign io_out = io_in[15] ? 32'h0 - shiftedMag : shiftedMag;
endmodule

module UIntFixedToBFloat16(
  input  [31:0] io_in,
  output [15:0] io_out
);

  wire [7:0]  _GEN =
    {{io_in[11:8], io_in[15:14]} & 6'h33, 2'h0} | {io_in[15:12], io_in[19:16]} & 8'h33;
  wire [18:0] _GEN_0 =
    {io_in[5:4], io_in[7:6], io_in[9:8], _GEN, io_in[19:18], io_in[21:20], io_in[23]}
    & 19'h55555;
  wire [3:0]  _GEN_1 = _GEN_0[18:15] | {io_in[7:6], io_in[9:8]} & 4'h5;
  wire [7:0]  _GEN_2 = _GEN_0[14:7] | _GEN & 8'h55;
  wire [3:0]  _GEN_3 = {_GEN_0[2:0], 1'h0} | {io_in[23:22], io_in[25:24]} & 4'h5;
  wire [4:0]  _msbIdx_T =
    5'h1F
    - (io_in[31]
         ? 5'h0
         : io_in[30]
             ? 5'h1
             : io_in[29]
                 ? 5'h2
                 : io_in[28]
                     ? 5'h3
                     : io_in[27]
                         ? 5'h4
                         : io_in[26]
                             ? 5'h5
                             : io_in[25]
                                 ? 5'h6
                                 : _GEN_3[0]
                                     ? 5'h7
                                     : _GEN_3[1]
                                         ? 5'h8
                                         : _GEN_3[2]
                                             ? 5'h9
                                             : _GEN_3[3]
                                                 ? 5'hA
                                                 : io_in[20]
                                                     ? 5'hB
                                                     : io_in[19]
                                                         ? 5'hC
                                                         : _GEN_0[5] | io_in[18]
                                                             ? 5'hD
                                                             : _GEN[1]
                                                                 ? 5'hE
                                                                 : _GEN_2[0]
                                                                     ? 5'hF
                                                                     : _GEN_2[1]
                                                                         ? 5'h10
                                                                         : _GEN_2[2]
                                                                             ? 5'h11
                                                                             : _GEN_2[3]
                                                                                 ? 5'h12
                                                                                 : _GEN_2[4]
                                                                                     ? 5'h13
                                                                                     : _GEN_2[5]
                                                                                         ? 5'h14
                                                                                         : _GEN_2[6]
                                                                                             ? 5'h15
                                                                                             : _GEN_2[7]
                                                                                                 ? 5'h16
                                                                                                 : _GEN_1[0]
                                                                                                     ? 5'h17
                                                                                                     : _GEN_1[1]
                                                                                                         ? 5'h18
                                                                                                         : _GEN_1[2]
                                                                                                             ? 5'h19
                                                                                                             : _GEN_1[3]
                                                                                                                 ? 5'h1A
                                                                                                                 : io_in[4]
                                                                                                                     ? 5'h1B
                                                                                                                     : io_in[3]
                                                                                                                         ? 5'h1C
                                                                                                                         : io_in[2]
                                                                                                                             ? 5'h1D
                                                                                                                             : {4'hF,
                                                                                                                                ~(io_in[1])});
  wire [6:0]  _unbiasedExp_T_1 = {2'h0, _msbIdx_T} - 7'h14;
  wire [7:0]  _biasedExp_T = {_unbiasedExp_T_1[6], _unbiasedExp_T_1} + 8'h7F;
  wire        shiftLeft = _msbIdx_T < 5'h7;
  wire [94:0] _normalizedSig_T =
    {63'h0, io_in} << (shiftLeft ? {1'h0, 5'h7 - _msbIdx_T} : 6'h0);
  wire [31:0] _normalizedSig_T_2 = io_in >> (shiftLeft ? 6'h0 : {1'h0, _msbIdx_T - 5'h7});
  assign io_out =
    io_in == 32'h0 | $signed(_biasedExp_T) < 8'sh1
      ? 16'h0
      : {1'h0, _biasedExp_T, shiftLeft ? _normalizedSig_T[6:0] : _normalizedSig_T_2[6:0]};
endmodule

module BFloat16Max(
  input  [15:0] io_in_1,
                io_in_2,
  output [15:0] io_out
);

  assign io_out =
    (io_in_1[15] == io_in_2[15]
       ? (io_in_1[15] ? io_in_2[14:0] > io_in_1[14:0] : io_in_1[14:0] > io_in_2[14:0])
       : ~(io_in_1[15]))
      ? io_in_1
      : io_in_2;
endmodule

module BFloat16VectorMax(
  input  [63:0] io_in,
  output [15:0] io_out
);

  wire [15:0] _io_out_T =
    (io_in[15] == io_in[31]
       ? (io_in[15] ? io_in[30:16] > io_in[14:0] : io_in[14:0] > io_in[30:16])
       : ~(io_in[15]))
      ? io_in[15:0]
      : io_in[31:16];
  wire [15:0] _io_out_T_1 =
    (io_in[47] == io_in[63]
       ? (io_in[47] ? io_in[62:48] > io_in[46:32] : io_in[46:32] > io_in[62:48])
       : ~(io_in[47]))
      ? io_in[47:32]
      : io_in[63:48];
  assign io_out =
    (_io_out_T[15] == _io_out_T_1[15]
       ? (_io_out_T[15]
            ? _io_out_T_1[14:0] > _io_out_T[14:0]
            : _io_out_T[14:0] > _io_out_T_1[14:0])
       : ~(_io_out_T[15]))
      ? _io_out_T
      : _io_out_T_1;
endmodule

module OnlineSoftmaxFastStandalone(
  input         clock,
                reset,
                io_cmdValid,
  output        io_cmdReady,
  input  [6:0]  io_cmdFunct,
  input  [63:0] io_cmdRs1,
                io_cmdRs2,
  input  [4:0]  io_cmdRd,
  output        io_respValid,
  input         io_respReady,
  output [4:0]  io_respRd,
  output [63:0] io_respData,
  output        io_memReqValid,
  input         io_memReqReady,
  output        io_memReqWrite,
  output [63:0] io_memReqAddr,
                io_memReqWdata,
  output [7:0]  io_memReqMask,
  input         io_memRespValid,
  output        io_memRespReady,
  input  [63:0] io_memRespData,
  output        io_busy
);

  wire [15:0]       _vecMax_io_out;
  wire [15:0]       _globalMax_io_out;
  wire [31:0]       _maxFixed_io_out;
  wire [15:0]       _maxExp_io_out;
  wire [15:0]       _maxSub_io_out;
  wire [15:0]       _vecNormOut_3_io_out;
  wire [15:0]       _vecNormOut_2_io_out;
  wire [15:0]       _vecNormOut_1_io_out;
  wire [15:0]       _vecNormOut_0_io_out;
  wire [31:0]       _vecFixed_3_io_out;
  wire [31:0]       _vecFixed_2_io_out;
  wire [31:0]       _vecFixed_1_io_out;
  wire [31:0]       _vecFixed_0_io_out;
  wire [15:0]       _vecExps_3_io_out;
  wire [15:0]       _vecExps_2_io_out;
  wire [15:0]       _vecExps_1_io_out;
  wire [15:0]       _vecExps_0_io_out;
  wire [15:0]       _vecSubs_3_io_out;
  wire [15:0]       _vecSubs_2_io_out;
  wire [15:0]       _vecSubs_1_io_out;
  wire [15:0]       _vecSubs_0_io_out;
  reg  [3:0]        state;
  reg  [31:0]       accum;
  reg  [15:0]       maxCurr;
  reg  [15:0]       maxPrev;
  reg  [63:0]       arraySize;
  reg  [63:0]       inBase;
  reg  [63:0]       inAddr;
  reg  [63:0]       outAddr;
  reg  [63:0]       procElements;
  reg  [63:0]       latchedData;
  reg  [31:0]       invSum;
  reg               doWrite;
  reg  [4:0]        respRd;
  reg  [63:0]       respData;
  wire [15:0]       bfloatInputs_0 =
    procElements >= arraySize ? 16'hFF80 : latchedData[15:0];
  wire [63:0]       _validBytes_3_T = procElements + 64'h1;
  wire [15:0]       bfloatInputs_1 =
    _validBytes_3_T >= arraySize ? 16'hFF80 : latchedData[31:16];
  wire [63:0]       _validBytes_5_T = procElements + 64'h2;
  wire [15:0]       bfloatInputs_2 =
    _validBytes_5_T >= arraySize ? 16'hFF80 : latchedData[47:32];
  wire [63:0]       _validBytes_7_T = procElements + 64'h3;
  wire [15:0]       bfloatInputs_3 =
    _validBytes_7_T >= arraySize ? 16'hFF80 : latchedData[63:48];
  wire [15:0]       subBase = doWrite ? maxPrev : _globalMax_io_out;
  wire [51:0]       _GEN = {20'h0, invSum};
  wire [51:0]       normFull = {20'h0, _vecFixed_0_io_out} * _GEN;
  wire [51:0]       normFull_1 = {20'h0, _vecFixed_1_io_out} * _GEN;
  wire [51:0]       normFull_2 = {20'h0, _vecFixed_2_io_out} * _GEN;
  wire [51:0]       normFull_3 = {20'h0, _vecFixed_3_io_out} * _GEN;
  wire              io_cmdReady_0 = state == 4'h0;
  wire              io_respValid_0 = state == 4'h8;
  wire              _GEN_0 = state == 4'h1;
  wire              _GEN_1 = state == 4'h2;
  wire              io_memReqWrite_0 = state == 4'h6;
  wire              _GEN_2 = state == 4'h7;
  wire [63:0][63:0] _GEN_3 =
    '{64'h4040404040404040,
      64'h40C246D47D78693C,
      64'h41465FDF5CD01052,
      64'h41CC98291FDF19B4,
      64'h4254FCE404254FCE,
      64'h42DF9BB096771E4D,
      64'h436C82A23D1A5663,
      64'h43FBC043FBC043FC,
      64'h448D639D74C0CDA8,
      64'h45217C382B34EDA3,
      64'h45B81A2509CDE3AD,
      64'h46514E02328A7012,
      64'h46ED29011BB4A404,
      64'h478BBCECFEE1D10C,
      64'h482D1C319F03621D,
      64'h48D159E26AF37C05,
      64'h497889C2024BC44E,
      64'h4A22C04A22C04A23,
      64'h4AD012B404AD012B,
      64'h4B8097012E025C05,
      64'h4C346404C346404C,
      64'h4CEB916D5EF2C783,
      64'h4DA637CF781D1E55,
      64'h4E6470B061FD8CDC,
      64'h4F265691EEAF9D10,
      64'h4FEC04FEC04FEC05,
      64'h50B59897547E1BBE,
      64'h51832F1FD73E6870,
      64'h5254E78ECB419BA9,
      64'h532AE21C96BDB9D4,
      64'h5405405405405405,
      64'h54E42523D03FAB1C,
      64'h55C7B4F141ACE689,
      64'h56B015AC056B015B,
      64'h579D6EE340579D6F,
      64'h588FE9DC0588FE9E,
      64'h5987B1A9448BE406,
      64'h5A84F3454DCA4110,
      64'h5B87DDAD0CDF1B2C,
      64'h5C90A1FD1B7AF017,
      64'h5D9F7390D2A6C406,
      64'h5EB4882383B30D51,
      64'h5FD017F405FD017F,
      64'h60F25DEACAFB74A4,
      64'h621B97C2AEC12653,
      64'h634C0634C0634C06,
      64'h6483ED274388A356,
      64'h65C393E032E1C9F0,
      64'h670B453B92840671,
      64'h685B4FE5E92C0686,
      64'h69B4069B4069B407,
      64'h6B15C06B15C06B16,
      64'h6C80D901B2036407,
      64'h6DF5B0F768CE2CAC,
      64'h6F74AE26501BDD2C,
      64'h70FE3C070FE3C071,
      64'h7292CC157B864407,
      64'h7432D63DBB01D0CB,
      64'h75DED952E0B0CE46,
      64'h77975B8FE21A291C,
      64'h795CEB240795CEB2,
      64'h7B301ECC07B301ED,
      64'h7D1196792909C560,
      64'h7F01FC07F01FC07F};
  wire [7:0]        _GEN_4 =
    {{accum[11:8], accum[15:14]} & 6'h33, 2'h0} | {accum[15:12], accum[19:16]} & 8'h33;
  wire [18:0]       _GEN_5 =
    {accum[5:4], accum[7:6], accum[9:8], _GEN_4, accum[19:18], accum[21:20], accum[23]}
    & 19'h55555;
  wire [3:0]        _GEN_6 = _GEN_5[18:15] | {accum[7:6], accum[9:8]} & 4'h5;
  wire [7:0]        _GEN_7 = _GEN_5[14:7] | _GEN_4 & 8'h55;
  wire [3:0]        _GEN_8 = {_GEN_5[2:0], 1'h0} | {accum[23:22], accum[25:24]} & 4'h5;
  wire [4:0]        shift =
    (|accum)
      ? 5'h1F
        - (accum[31]
             ? 5'h0
             : accum[30]
                 ? 5'h1
                 : accum[29]
                     ? 5'h2
                     : accum[28]
                         ? 5'h3
                         : accum[27]
                             ? 5'h4
                             : accum[26]
                                 ? 5'h5
                                 : accum[25]
                                     ? 5'h6
                                     : _GEN_8[0]
                                         ? 5'h7
                                         : _GEN_8[1]
                                             ? 5'h8
                                             : _GEN_8[2]
                                                 ? 5'h9
                                                 : _GEN_8[3]
                                                     ? 5'hA
                                                     : accum[20]
                                                         ? 5'hB
                                                         : accum[19]
                                                             ? 5'hC
                                                             : _GEN_5[5] | accum[18]
                                                                 ? 5'hD
                                                                 : _GEN_4[1]
                                                                     ? 5'hE
                                                                     : _GEN_7[0]
                                                                         ? 5'hF
                                                                         : _GEN_7[1]
                                                                             ? 5'h10
                                                                             : _GEN_7[2]
                                                                                 ? 5'h11
                                                                                 : _GEN_7[3]
                                                                                     ? 5'h12
                                                                                     : _GEN_7[4]
                                                                                         ? 5'h13
                                                                                         : _GEN_7[5]
                                                                                             ? 5'h14
                                                                                             : _GEN_7[6]
                                                                                                 ? 5'h15
                                                                                                 : _GEN_7[7]
                                                                                                     ? 5'h16
                                                                                                     : _GEN_6[0]
                                                                                                         ? 5'h17
                                                                                                         : _GEN_6[1]
                                                                                                             ? 5'h18
                                                                                                             : _GEN_6[2]
                                                                                                                 ? 5'h19
                                                                                                                 : _GEN_6[3]
                                                                                                                     ? 5'h1A
                                                                                                                     : accum[4]
                                                                                                                         ? 5'h1B
                                                                                                                         : accum[3]
                                                                                                                             ? 5'h1C
                                                                                                                             : accum[2]
                                                                                                                                 ? 5'h1D
                                                                                                                                 : {4'hF,
                                                                                                                                    ~(accum[1])})
        + 5'hC
      : 5'h0;
  wire [31:0]       mant = accum >> shift;
  wire              _GEN_9 = io_cmdValid & io_cmdReady_0;
  wire              _GEN_10 = _GEN_9 & ~(|io_cmdFunct);
  wire              _GEN_11 = _GEN_9 & (|io_cmdFunct);
  wire              _GEN_12 = _GEN_1 & io_memRespValid;
  wire              _GEN_13 = state == 4'h3;
  wire              _GEN_14 = state == 4'h5;
  wire [51:0]       prodAccumFull =
    {20'h0, accum}
    * {20'h0, _maxFixed_io_out > 32'h100000 ? 32'h100000 : _maxFixed_io_out};
  wire [31:0]       _respData_T =
    _vecFixed_0_io_out + _vecFixed_1_io_out + _vecFixed_2_io_out + _vecFixed_3_io_out
    + prodAccumFull[51:20];
  wire [63:0]       _nextProcElements_T = procElements + 64'h4;
  wire              _GEN_15 = _nextProcElements_T >= arraySize;
  wire              _GEN_16 = _GEN_2 & io_memRespValid;
  wire [63:0]       _nextProcElements_T_1 = procElements + 64'h4;
  always @(posedge clock) begin
    if (reset) begin
      state <= 4'h0;
      accum <= 32'h0;
      maxCurr <= 16'hFF80;
      maxPrev <= 16'hFF80;
      arraySize <= 64'h0;
      inBase <= 64'h0;
      inAddr <= 64'h0;
      outAddr <= 64'h0;
      procElements <= 64'h0;
      latchedData <= 64'h0;
      invSum <= 32'h0;
      doWrite <= 1'h0;
      respRd <= 5'h0;
      respData <= 64'h0;
    end
    else begin
      if (io_respValid_0 & io_respReady)
        state <= 4'h0;
      else if (_GEN_16)
        state <= _nextProcElements_T_1 >= arraySize ? 4'h8 : 4'h1;
      else if (io_memReqWrite_0 & io_memReqReady)
        state <= 4'h7;
      else if (_GEN_14)
        state <= _GEN_15 ? 4'h8 : 4'h1;
      else if (state == 4'h4)
        state <= doWrite ? 4'h6 : 4'h5;
      else if (_GEN_13)
        state <= 4'h4;
      else if (_GEN_12)
        state <= doWrite ? 4'h4 : 4'h3;
      else if (_GEN_0 & io_memReqReady)
        state <= 4'h2;
      else if (_GEN_9)
        state <= ((|io_cmdFunct) ? arraySize == 64'h0 : io_cmdRs2 == 64'h0) ? 4'h8 : 4'h1;
      if (_GEN_14) begin
        accum <= _respData_T;
        maxPrev <= maxCurr;
      end
      else if (_GEN_10) begin
        accum <= 32'h0;
        maxPrev <= 16'hFF80;
      end
      if (_GEN_13)
        maxCurr <= _globalMax_io_out;
      if (_GEN_10) begin
        arraySize <= io_cmdRs2;
        inBase <= io_cmdRs1;
      end
      if (_GEN_16) begin
        inAddr <= inAddr + 64'h8;
        outAddr <= outAddr + 64'h8;
        procElements <= _nextProcElements_T_1;
      end
      else begin
        if (_GEN_14) begin
          inAddr <= inAddr + 64'h8;
          procElements <= _nextProcElements_T;
        end
        else if (_GEN_9) begin
          inAddr <= (|io_cmdFunct) ? inBase : io_cmdRs1;
          procElements <= 64'h0;
        end
        if (_GEN_11)
          outAddr <= io_cmdRs1;
      end
      if (_GEN_12)
        latchedData <= io_memRespData;
      if (_GEN_11)
        invSum <= (|accum) ? {11'h0, _GEN_3[mant[20:15]][63:43] >> shift} : 32'h0;
      if (_GEN_9) begin
        doWrite <= |io_cmdFunct;
        respRd <= io_cmdRd;
      end
      if (_GEN_14 & _GEN_15)
        respData <= {32'h0, _respData_T};
      else if (_GEN_9)
        respData <= 64'h0;
    end
  end // always @(posedge)
  BFloat16Sub vecSubs_0 (
    .io_in_1 (bfloatInputs_0),
    .io_in_2 (subBase),
    .io_out  (_vecSubs_0_io_out)
  );
  BFloat16Sub vecSubs_1 (
    .io_in_1 (bfloatInputs_1),
    .io_in_2 (subBase),
    .io_out  (_vecSubs_1_io_out)
  );
  BFloat16Sub vecSubs_2 (
    .io_in_1 (bfloatInputs_2),
    .io_in_2 (subBase),
    .io_out  (_vecSubs_2_io_out)
  );
  BFloat16Sub vecSubs_3 (
    .io_in_1 (bfloatInputs_3),
    .io_in_2 (subBase),
    .io_out  (_vecSubs_3_io_out)
  );
  BFloat16Exp vecExps_0 (
    .io_in  (_vecSubs_0_io_out),
    .io_out (_vecExps_0_io_out)
  );
  BFloat16Exp vecExps_1 (
    .io_in  (_vecSubs_1_io_out),
    .io_out (_vecExps_1_io_out)
  );
  BFloat16Exp vecExps_2 (
    .io_in  (_vecSubs_2_io_out),
    .io_out (_vecExps_2_io_out)
  );
  BFloat16Exp vecExps_3 (
    .io_in  (_vecSubs_3_io_out),
    .io_out (_vecExps_3_io_out)
  );
  BFloat16ToFixed vecFixed_0 (
    .io_in  (_vecExps_0_io_out),
    .io_out (_vecFixed_0_io_out)
  );
  BFloat16ToFixed vecFixed_1 (
    .io_in  (_vecExps_1_io_out),
    .io_out (_vecFixed_1_io_out)
  );
  BFloat16ToFixed vecFixed_2 (
    .io_in  (_vecExps_2_io_out),
    .io_out (_vecFixed_2_io_out)
  );
  BFloat16ToFixed vecFixed_3 (
    .io_in  (_vecExps_3_io_out),
    .io_out (_vecFixed_3_io_out)
  );
  UIntFixedToBFloat16 vecNormOut_0 (
    .io_in  (normFull[51:20]),
    .io_out (_vecNormOut_0_io_out)
  );
  UIntFixedToBFloat16 vecNormOut_1 (
    .io_in  (normFull_1[51:20]),
    .io_out (_vecNormOut_1_io_out)
  );
  UIntFixedToBFloat16 vecNormOut_2 (
    .io_in  (normFull_2[51:20]),
    .io_out (_vecNormOut_2_io_out)
  );
  UIntFixedToBFloat16 vecNormOut_3 (
    .io_in  (normFull_3[51:20]),
    .io_out (_vecNormOut_3_io_out)
  );
  BFloat16Sub maxSub (
    .io_in_1 (maxPrev),
    .io_in_2 (_globalMax_io_out),
    .io_out  (_maxSub_io_out)
  );
  BFloat16Exp maxExp (
    .io_in  (_maxSub_io_out),
    .io_out (_maxExp_io_out)
  );
  BFloat16ToFixed maxFixed (
    .io_in  (_maxExp_io_out),
    .io_out (_maxFixed_io_out)
  );
  BFloat16Max globalMax (
    .io_in_1 (_vecMax_io_out),
    .io_in_2 (maxPrev),
    .io_out  (_globalMax_io_out)
  );
  BFloat16VectorMax vecMax (
    .io_in  ({bfloatInputs_3, bfloatInputs_2, bfloatInputs_1, bfloatInputs_0}),
    .io_out (_vecMax_io_out)
  );
  assign io_cmdReady = io_cmdReady_0;
  assign io_respValid = io_respValid_0;
  assign io_respRd = respRd;
  assign io_respData = respData;
  assign io_memReqValid = io_memReqWrite_0 | _GEN_0;
  assign io_memReqWrite = io_memReqWrite_0;
  assign io_memReqAddr = io_memReqWrite_0 ? outAddr : _GEN_0 ? inAddr : 64'h0;
  assign io_memReqWdata =
    io_memReqWrite_0
      ? {_validBytes_7_T < arraySize ? _vecNormOut_3_io_out : 16'h0,
         _validBytes_5_T < arraySize ? _vecNormOut_2_io_out : 16'h0,
         _validBytes_3_T < arraySize ? _vecNormOut_1_io_out : 16'h0,
         procElements < arraySize ? _vecNormOut_0_io_out : 16'h0}
      : 64'h0;
  assign io_memReqMask =
    io_memReqWrite_0
      ? {_validBytes_7_T < arraySize,
         _validBytes_7_T < arraySize,
         _validBytes_5_T < arraySize,
         _validBytes_5_T < arraySize,
         _validBytes_3_T < arraySize,
         _validBytes_3_T < arraySize,
         procElements < arraySize,
         procElements < arraySize}
      : {8{_GEN_0}};
  assign io_memRespReady = _GEN_2 | _GEN_1;
  assign io_busy = |state;
endmodule

module OnlineSoftmaxFastOpenLaneTop(
  input         clock,
                reset,
                io_cmdValid,
  output        io_cmdReady,
  input  [6:0]  io_cmdFunct,
  input  [63:0] io_cmdRs1,
                io_cmdRs2,
  input  [4:0]  io_cmdRd,
  output        io_respValid,
  input         io_respReady,
  output [4:0]  io_respRd,
  output [63:0] io_respData,
  output        io_memReqValid,
  input         io_memReqReady,
  output        io_memReqWrite,
  output [63:0] io_memReqAddr,
                io_memReqWdata,
  output [7:0]  io_memReqMask,
  input         io_memRespValid,
  output        io_memRespReady,
  input  [63:0] io_memRespData,
  input         io_memRespWriteAck,
  output        io_busy
);

  OnlineSoftmaxFastStandalone dut (
    .clock           (clock),
    .reset           (reset),
    .io_cmdValid     (io_cmdValid),
    .io_cmdReady     (io_cmdReady),
    .io_cmdFunct     (io_cmdFunct),
    .io_cmdRs1       (io_cmdRs1),
    .io_cmdRs2       (io_cmdRs2),
    .io_cmdRd        (io_cmdRd),
    .io_respValid    (io_respValid),
    .io_respReady    (io_respReady),
    .io_respRd       (io_respRd),
    .io_respData     (io_respData),
    .io_memReqValid  (io_memReqValid),
    .io_memReqReady  (io_memReqReady),
    .io_memReqWrite  (io_memReqWrite),
    .io_memReqAddr   (io_memReqAddr),
    .io_memReqWdata  (io_memReqWdata),
    .io_memReqMask   (io_memReqMask),
    .io_memRespValid (io_memRespValid),
    .io_memRespReady (io_memRespReady),
    .io_memRespData  (io_memRespData),
    .io_busy         (io_busy)
  );
endmodule

