// Generated by CIRCT firtool-1.75.0
module AddRecFN(	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:133:7]
  input  [17:0] io_a,	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:135:16]
  input  [17:0] io_b,	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:135:16]
  output [17:0] io_out	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:135:16]
);

  wire        _addRawFN_io_invalidExc;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire        _addRawFN_io_rawOut_isNaN;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire        _addRawFN_io_rawOut_isInf;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire        _addRawFN_io_rawOut_isZero;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire        _addRawFN_io_rawOut_sign;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire [9:0]  _addRawFN_io_rawOut_sExp;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  wire [11:0] _addRawFN_io_rawOut_sig;	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  AddRawFN addRawFN (	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_a_isNaN       ((&(io_a[16:15])) & io_a[14]),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}]
    .io_a_isInf       ((&(io_a[16:15])) & ~(io_a[14])),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}]
    .io_a_isZero      (~(|(io_a[16:14]))),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}]
    .io_a_sign        (io_a[17]),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25]
    .io_a_sExp        ({1'h0, io_a[16:8]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27]
    .io_a_sig         ({1'h0, |(io_a[16:14]), io_a[7:0]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}]
    .io_b_isNaN       ((&(io_b[16:15])) & io_b[14]),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}]
    .io_b_isInf       ((&(io_b[16:15])) & ~(io_b[14])),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}]
    .io_b_isZero      (~(|(io_b[16:14]))),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}]
    .io_b_sign        (io_b[17]),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25]
    .io_b_sExp        ({1'h0, io_b[16:8]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27]
    .io_b_sig         ({1'h0, |(io_b[16:14]), io_b[7:0]}),	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, :61:{44,49}]
    .io_invalidExc    (_addRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_addRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_addRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_addRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_addRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_addRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_addRawFN_io_rawOut_sig)
  );	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
  RoundRawFNToRecFN_e8_s9 roundRawFNToRecFN (	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:157:15]
    .io_invalidExc (_addRawFN_io_invalidExc),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_isNaN   (_addRawFN_io_rawOut_isNaN),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_isInf   (_addRawFN_io_rawOut_isInf),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_isZero  (_addRawFN_io_rawOut_isZero),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_sign    (_addRawFN_io_rawOut_sign),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_sExp    (_addRawFN_io_rawOut_sExp),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_in_sig     (_addRawFN_io_rawOut_sig),	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:147:26]
    .io_out        (io_out)
  );	// @[generators/hardfloat/hardfloat/src/main/scala/AddRecFN.scala:157:15]
endmodule

