// Generated by CIRCT firtool-1.75.0
module BFloat16ToSIntFixed(	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:41:7]
  input  [15:0] io_in,	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:48:14]
  output [23:0] io_out	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:48:14]
);

  wire [9:0]    _shiftAmt_T_3 = ((|(io_in[14:7])) ? {2'h0, io_in[14:7]} : 10'h1) - 10'h76;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:54:18, :57:30, :60:{19,67}, :61:{25,31}]
  wire [1031:0] _shiftedMag_T_3 = {1024'h0, |(io_in[14:7]), io_in[6:0]} << _shiftAmt_T_3;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:54:18, :55:23, :57:30, :60:67, :61:{25,31}, :67:44]
  wire [9:0]    _shiftedMag_T_11 = {2'h0, |(io_in[14:7]), io_in[6:0]} >> 10'h0 - _shiftAmt_T_3;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:54:18, :55:23, :57:30, :60:67, :61:{25,31}, :66:23, :69:{43,47}]
  wire [31:0]   shiftedMag = io_in[14:0] == 15'h0 ? 32'h0 : $signed(_shiftAmt_T_3) > -10'sh1 ? _shiftedMag_T_3[31:0] : {23'h0, _shiftedMag_T_11[8:0]};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:60:67, :61:{25,31}, :64:{13,21,30}, :65:16, :66:{23,31}, :67:{16,44,63}, :69:{16,43}]
  wire [31:0]   satMag = ~(io_in[15]) & (|(shiftedMag[31:23])) ? 32'h7FFFFF : io_in[15] & shiftedMag > 32'h800000 ? 32'h800000 : shiftedMag;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:53:19, :64:30, :65:16, :66:31, :75:{13,21,35,48}, :76:12, :77:{27,41,54}, :78:12, :80:12]
  assign io_out = io_in[15] & (|satMag) ? 24'h0 - satMag[23:0] : satMag[23:0];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:41:7, :53:19, :75:48, :76:12, :77:54, :83:22, :84:17, :85:{16,30,40}]
endmodule

