// Generated by CIRCT firtool-1.75.0
module BFloat16VectorMax(	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:245:7]
  input  [127:0] io_in,	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:246:14]
  output [15:0]  io_out	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:246:14]
);

  wire [15:0] _io_out_T = (io_in[15] == io_in[31] ? (io_in[15] ? io_in[30:16] > io_in[14:0] : io_in[14:0] > io_in[30:16]) : ~(io_in[15])) ? io_in[15:0] : io_in[31:16];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8, :252:10]
  wire [15:0] _io_out_T_1 = (io_in[47] == io_in[63] ? (io_in[47] ? io_in[62:48] > io_in[46:32] : io_in[46:32] > io_in[62:48]) : ~(io_in[47])) ? io_in[47:32] : io_in[63:48];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8, :252:10]
  wire [15:0] _io_out_T_2 = (io_in[79] == io_in[95] ? (io_in[79] ? io_in[94:80] > io_in[78:64] : io_in[78:64] > io_in[94:80]) : ~(io_in[79])) ? io_in[79:64] : io_in[95:80];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8, :252:10]
  wire [15:0] _io_out_T_3 = (io_in[111] == io_in[127] ? (io_in[111] ? io_in[126:112] > io_in[110:96] : io_in[110:96] > io_in[126:112]) : ~(io_in[111])) ? io_in[111:96] : io_in[127:112];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8, :252:10]
  wire [15:0] _io_out_T_4 = (_io_out_T[15] == _io_out_T_1[15] ? (_io_out_T[15] ? _io_out_T_1[14:0] > _io_out_T[14:0] : _io_out_T[14:0] > _io_out_T_1[14:0]) : ~(_io_out_T[15])) ? _io_out_T : _io_out_T_1;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8]
  wire [15:0] _io_out_T_5 = (_io_out_T_2[15] == _io_out_T_3[15] ? (_io_out_T_2[15] ? _io_out_T_3[14:0] > _io_out_T_2[14:0] : _io_out_T_2[14:0] > _io_out_T_3[14:0]) : ~(_io_out_T_2[15])) ? _io_out_T_2 : _io_out_T_3;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8]
  assign io_out = (_io_out_T_4[15] == _io_out_T_5[15] ? (_io_out_T_4[15] ? _io_out_T_5[14:0] > _io_out_T_4[14:0] : _io_out_T_4[14:0] > _io_out_T_5[14:0]) : ~(_io_out_T_4[15])) ? _io_out_T_4 : _io_out_T_5;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:221:18, :222:18, :223:17, :224:17, :226:24, :227:13, :228:13, :229:{10,31,44}, :231:8, :245:7]
endmodule

