// Generated by CIRCT firtool-1.75.0
module BFloat16Exp(	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:258:7]
  input  [15:0] io_in,	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:259:14]
  output [15:0] io_out	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:259:14]
);

  wire [24:0] shiftedMantissa = {{10'h0, io_in[14:7] == 8'h0 ? 8'h0 : {1'h1, io_in[6:0]}} * 18'h171, 7'h0} >> 8'h85 - io_in[14:7];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:265:23, :266:26, :272:{21,31,53}, :274:33, :275:27, :277:21, :278:40]
  wire [14:0] signedMantissa = {15{io_in[15]}} ^ shiftedMantissa[23:9];	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:264:19, :278:40, :279:27]
  wire [9:0]  _GEN = {3'h0, signedMantissa[6:0]};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:279:27, :281:29, :283:24, :286:27, :291:26]
  wire [20:0] p1 = {4'h0, {7'h0, _GEN + 10'h1A6} * 17'h1C} * {14'h0, signedMantissa[6:0]};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:279:27, :281:29, :286:27, :291:{26,37,45}]
  wire [20:0] p2 = {4'h0, {7'h0, _GEN + 10'h116} * 17'h38} * {14'h0, ~(signedMantissa[6:0])};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:279:27, :281:29, :286:27, :287:26, :291:26, :295:{26,37,44}]
  assign io_out = (&(io_in[14:7])) & io_in[6:0] == 7'h0 & io_in[15] ? 16'h0 : (&(io_in[14:7])) ? 16'h7F7F : {1'h0, signedMantissa[14:7] + 8'h7F, signedMantissa[6] ? p1[20:14] : ~(p2[20:14])};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:258:7, :264:19, :265:23, :266:26, :268:27, :269:36, :270:{27,45}, :279:27, :281:29, :283:24, :286:27, :291:45, :295:44, :297:33, :298:{26,42,52,56}, :299:22, :302:{16,35}]
endmodule

