// Generated by CIRCT firtool-1.75.0
module BFloat16ToFixed(	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:7:7]
  input  [15:0] io_in,	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:8:14]
  output [31:0] io_out	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:8:14]
);

  wire [8:0]   _shiftAmt_T_3 = ((|(io_in[14:7])) ? {1'h0, io_in[14:7]} : 9'h1) - 9'h72;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:13:18, :16:30, :21:{19,52,58}, :22:{25,31}]
  wire [518:0] _shiftedMag_T_1 = {511'h0, |(io_in[14:7]), io_in[6:0]} << _shiftAmt_T_3;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:13:18, :14:23, :16:30, :21:58, :22:{25,31}, :26:31]
  wire [8:0]   _shiftedMag_T_6 = {1'h0, |(io_in[14:7]), io_in[6:0]} >> 9'h0 - _shiftAmt_T_3;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:13:18, :14:23, :16:30, :21:58, :22:{25,31}, :25:17, :28:{31,35}]
  wire [31:0]  shiftedMag = $signed(_shiftAmt_T_3) > -9'sh1 ? _shiftedMag_T_1[31:0] : {24'h0, _shiftedMag_T_6[7:0]};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:21:58, :22:{25,31}, :25:{17,25}, :26:{16,31}, :28:{16,31}]
  assign io_out = io_in[15] ? 32'h0 - shiftedMag : shiftedMag;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:7:7, :12:19, :25:{17,25}, :26:16, :28:16, :32:22, :33:{13,16}, :35:13]
endmodule

