// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module RoccCommandRouter(	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7]
  output        io_in_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [6:0]  io_in_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_inst_xs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [4:0]  io_in_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [6:0]  io_in_bits_inst_opcode,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [63:0] io_in_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [63:0] io_in_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_debug,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_cease,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_wfi,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [31:0] io_in_bits_status_isa,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_dprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_dv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_prv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_v,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mpv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_gva,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tsr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tw,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_tvm,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mxr,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_sum,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mprv,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_fs,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input  [1:0]  io_in_bits_status_mpp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_spp,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mpie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_spie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_mie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_in_bits_status_sie,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_out_0_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_0_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [6:0]  io_out_0_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [4:0]  io_out_0_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_0_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_0_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  input         io_out_1_ready,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_out_1_valid,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [6:0]  io_out_1_bits_inst_funct,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [4:0]  io_out_1_bits_inst_rd,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_1_bits_rs1,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output [63:0] io_out_1_bits_rs2,	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
  output        io_busy	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:402:14]
);

  wire        _cmd_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [6:0]  _cmd_q_io_deq_bits_inst_funct;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [4:0]  _cmd_q_io_deq_bits_inst_rd;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [6:0]  _cmd_q_io_deq_bits_inst_opcode;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [63:0] _cmd_q_io_deq_bits_rs1;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [63:0] _cmd_q_io_deq_bits_rs2;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        cmdReadys_me = _cmd_q_io_deq_bits_inst_opcode == 7'hB;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        cmdReadys_0 = io_out_0_ready & cmdReadys_me;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :413:15]
  wire        cmdReadys_me_1 = _cmd_q_io_deq_bits_inst_opcode == 7'h2B;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        cmdReadys_1 = io_out_1_ready & cmdReadys_me_1;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :413:15]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
    wire [1:0] _GEN = {1'h0, cmdReadys_0} + {1'h0, cmdReadys_1};	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:413:15, :418:18]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
      if (~reset & _GEN[1]) begin	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:{9,18,30}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
          $error("Assertion failed: Custom opcode matched for more than one accelerator\n    at LazyRoCC.scala:418 assert(PopCount(cmdReadys) <= 1.U,\n");	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:418:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  Queue2_RoCCCommand cmd_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                    (clock),
    .reset                    (reset),
    .io_enq_ready             (io_in_ready),
    .io_enq_valid             (io_in_valid),
    .io_enq_bits_inst_funct   (io_in_bits_inst_funct),
    .io_enq_bits_inst_rs2     (io_in_bits_inst_rs2),
    .io_enq_bits_inst_rs1     (io_in_bits_inst_rs1),
    .io_enq_bits_inst_xd      (io_in_bits_inst_xd),
    .io_enq_bits_inst_xs1     (io_in_bits_inst_xs1),
    .io_enq_bits_inst_xs2     (io_in_bits_inst_xs2),
    .io_enq_bits_inst_rd      (io_in_bits_inst_rd),
    .io_enq_bits_inst_opcode  (io_in_bits_inst_opcode),
    .io_enq_bits_rs1          (io_in_bits_rs1),
    .io_enq_bits_rs2          (io_in_bits_rs2),
    .io_enq_bits_status_debug (io_in_bits_status_debug),
    .io_enq_bits_status_cease (io_in_bits_status_cease),
    .io_enq_bits_status_wfi   (io_in_bits_status_wfi),
    .io_enq_bits_status_isa   (io_in_bits_status_isa),
    .io_enq_bits_status_dprv  (io_in_bits_status_dprv),
    .io_enq_bits_status_dv    (io_in_bits_status_dv),
    .io_enq_bits_status_prv   (io_in_bits_status_prv),
    .io_enq_bits_status_v     (io_in_bits_status_v),
    .io_enq_bits_status_mpv   (io_in_bits_status_mpv),
    .io_enq_bits_status_gva   (io_in_bits_status_gva),
    .io_enq_bits_status_tsr   (io_in_bits_status_tsr),
    .io_enq_bits_status_tw    (io_in_bits_status_tw),
    .io_enq_bits_status_tvm   (io_in_bits_status_tvm),
    .io_enq_bits_status_mxr   (io_in_bits_status_mxr),
    .io_enq_bits_status_sum   (io_in_bits_status_sum),
    .io_enq_bits_status_mprv  (io_in_bits_status_mprv),
    .io_enq_bits_status_fs    (io_in_bits_status_fs),
    .io_enq_bits_status_mpp   (io_in_bits_status_mpp),
    .io_enq_bits_status_spp   (io_in_bits_status_spp),
    .io_enq_bits_status_mpie  (io_in_bits_status_mpie),
    .io_enq_bits_status_spie  (io_in_bits_status_spie),
    .io_enq_bits_status_mie   (io_in_bits_status_mie),
    .io_enq_bits_status_sie   (io_in_bits_status_sie),
    .io_deq_ready             (cmdReadys_0 | cmdReadys_1),	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:413:15, :415:35]
    .io_deq_valid             (_cmd_q_io_deq_valid),
    .io_deq_bits_inst_funct   (_cmd_q_io_deq_bits_inst_funct),
    .io_deq_bits_inst_rd      (_cmd_q_io_deq_bits_inst_rd),
    .io_deq_bits_inst_opcode  (_cmd_q_io_deq_bits_inst_opcode),
    .io_deq_bits_rs1          (_cmd_q_io_deq_bits_rs1),
    .io_deq_bits_rs2          (_cmd_q_io_deq_bits_rs2)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_valid = _cmd_q_io_deq_valid & cmdReadys_me;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :400:7, :411:28, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_bits_inst_funct = _cmd_q_io_deq_bits_inst_funct;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_bits_inst_rd = _cmd_q_io_deq_bits_inst_rd;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_bits_rs1 = _cmd_q_io_deq_bits_rs1;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_0_bits_rs2 = _cmd_q_io_deq_bits_rs2;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_1_valid = _cmd_q_io_deq_valid & cmdReadys_me_1;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:389:41, :400:7, :411:28, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_1_bits_inst_funct = _cmd_q_io_deq_bits_inst_funct;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_1_bits_inst_rd = _cmd_q_io_deq_bits_inst_rd;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_1_bits_rs1 = _cmd_q_io_deq_bits_rs1;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_out_1_bits_rs2 = _cmd_q_io_deq_bits_rs2;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_busy = _cmd_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tile/LazyRoCC.scala:400:7, src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

