// Generated by CIRCT firtool-1.75.0
module RoundAnyRawFNToRecFN_ie8_is11_oe8_os9(	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:48:5]
  input         io_invalidExc,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input         io_in_isNaN,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input         io_in_isInf,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input         io_in_isZero,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input         io_in_sign,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input  [9:0]  io_in_sExp,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  input  [11:0] io_in_sig,	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
  output [17:0] io_out	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16]
);

  wire [8:0]  _roundMask_T_1 = ~(io_in_sExp[8:0]);	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:156:37, generators/hardfloat/hardfloat/src/main/scala/primitives.scala:52:21]
  wire [64:0] _GEN = {59'h0, _roundMask_T_1[5:0]};	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:52:21, :59:26, :76:56]
  wire [64:0] roundMask_shift = $signed(65'sh10000000000000000 >>> _GEN);	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:76:56]
  wire [64:0] roundMask_shift_1 = $signed(65'sh10000000000000000 >>> _GEN);	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:76:56]
  wire [9:0]  _roundMask_T_34 = _roundMask_T_1[8] ? (_roundMask_T_1[7] ? {~(_roundMask_T_1[6] ? 7'h0 : ~{roundMask_shift[57], roundMask_shift[58], roundMask_shift[59], roundMask_shift[60], roundMask_shift[61], roundMask_shift[62], roundMask_shift[63]}), 3'h7} : {7'h0, _roundMask_T_1[6] ? {roundMask_shift_1[0], roundMask_shift_1[1], roundMask_shift_1[2]} : 3'h0}) : 10'h0;	// @[generators/hardfloat/hardfloat/src/main/scala/primitives.scala:52:21, :58:25, :59:26, :62:24, :67:24, :68:58, :73:{17,21,32}, :76:56, :77:20, :78:22]
  wire        _GEN_0 = _roundMask_T_34[0] | io_in_sig[11];	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:120:57, :159:23, generators/hardfloat/hardfloat/src/main/scala/primitives.scala:62:24]
  wire [10:0] _GEN_1 = {_roundMask_T_34[9:1], _GEN_0, 1'h1};	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:159:{23,42}, generators/hardfloat/hardfloat/src/main/scala/primitives.scala:62:24]
  wire [10:0] _roundPosBit_T = io_in_sig[11:1] & {1'h1, ~(_roundMask_T_34[9:1]), ~_GEN_0} & _GEN_1;	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :162:53, :163:{28,46}, :164:40, generators/hardfloat/hardfloat/src/main/scala/primitives.scala:62:24]
  wire [10:0] roundedSig = (|_roundPosBit_T) ? {1'h0, io_in_sig[11:2] | {_roundMask_T_34[9:1], _GEN_0}} + 11'h1 & ~((|_roundPosBit_T) & (io_in_sig[10:0] & _GEN_1) == 11'h0 ? {_roundMask_T_34[9:1], _GEN_0, 1'h1} : 11'h0) : {1'h0, io_in_sig[11:2] & {~(_roundMask_T_34[9:1]), ~_GEN_0}};	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:58:16, :159:{23,42}, :163:{28,46}, :164:{40,56}, :165:{42,62}, :173:16, :174:{32,49,57}, :175:{21,25,64}, :177:35, :180:{30,43,47}, generators/hardfloat/hardfloat/src/main/scala/primitives.scala:62:24]
  wire [10:0] sRoundedExp = {io_in_sExp[9], io_in_sExp} + {9'h0, roundedSig[10:9]};	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:173:16, :185:{40,54}]
  wire        common_totalUnderflow = $signed(sRoundedExp) < 11'sh7A;	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:185:40, :200:31]
  wire        isNaNOut = io_invalidExc | io_in_isNaN;	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:235:34]
  wire        notNaN_isInfOut = io_in_isInf | ~isNaNOut & ~io_in_isInf & ~io_in_isZero & $signed(sRoundedExp[10:7]) > 4'sh2;	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:185:40, :196:{30,50}, :235:34, :237:{22,33,36,61,64}, :238:32, :248:32]
  assign io_out = {~isNaNOut & io_in_sign, sRoundedExp[8:0] & ~(io_in_isZero | common_totalUnderflow ? 9'h1C0 : 9'h0) & {2'h3, ~notNaN_isInfOut, 6'h3F} | (notNaN_isInfOut ? 9'h180 : 9'h0) | (isNaNOut ? 9'h1C0 : 9'h0), isNaNOut | io_in_isZero | common_totalUnderflow ? {isNaNOut, 7'h0} : io_in_sig[11] ? roundedSig[8:1] : roundedSig[7:0]};	// @[generators/hardfloat/hardfloat/src/main/scala/RoundAnyRawFNToRecFN.scala:48:5, :120:57, :173:16, :185:40, :187:37, :189:16, :190:27, :191:27, :200:31, :235:34, :248:32, :250:22, :252:24, :253:{14,18,32}, :264:17, :265:{14,18}, :276:15, :277:{16,73}, :278:16, :280:{12,22,38}, :281:16, :286:33]
endmodule

