// Generated by CIRCT firtool-1.75.0
module UIntFixedToBFloat16(	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:88:7]
  input  [31:0] io_in,	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:98:14]
  output [15:0] io_out	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:98:14]
);

  wire [18:0] _GEN = {io_in[5:4], io_in[7:6], io_in[9:8], io_in[11:10], io_in[13:12], io_in[15:14], io_in[17:16], io_in[19:18], io_in[21:20], io_in[23]} & 19'h55555;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:106:45]
  wire [3:0]  _GEN_0 = _GEN[18:15] | {io_in[7:6], io_in[9:8]} & 4'h5;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:106:45]
  wire [3:0]  _GEN_1 = _GEN[10:7] | {io_in[15:14], io_in[17:16]} & 4'h5;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:106:45]
  wire [3:0]  _GEN_2 = {_GEN[2:0], 1'h0} | {io_in[23:22], io_in[25:24]} & 4'h5;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:106:45]
  wire [4:0]  _msbIdx_T = 5'h1F - (io_in[31] ? 5'h0 : io_in[30] ? 5'h1 : io_in[29] ? 5'h2 : io_in[28] ? 5'h3 : io_in[27] ? 5'h4 : io_in[26] ? 5'h5 : io_in[25] ? 5'h6 : _GEN_2[0] ? 5'h7 : _GEN_2[1] ? 5'h8 : _GEN_2[2] ? 5'h9 : _GEN_2[3] ? 5'hA : io_in[20] ? 5'hB : io_in[19] ? 5'hC : _GEN[5] | io_in[18] ? 5'hD : io_in[17] ? 5'hE : _GEN_1[0] ? 5'hF : _GEN_1[1] ? 5'h10 : _GEN_1[2] ? 5'h11 : _GEN_1[3] ? 5'h12 : io_in[12] ? 5'h13 : io_in[11] ? 5'h14 : _GEN[13] | io_in[10] ? 5'h15 : io_in[9] ? 5'h16 : _GEN_0[0] ? 5'h17 : _GEN_0[1] ? 5'h18 : _GEN_0[2] ? 5'h19 : _GEN_0[3] ? 5'h1A : io_in[4] ? 5'h1B : io_in[3] ? 5'h1C : io_in[2] ? 5'h1D : {4'hF, ~(io_in[1])});	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:106:45, :107:33, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:48:45]
  wire [6:0]  _unbiasedExp_T_1 = {2'h0, _msbIdx_T} - 7'h14;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:107:33, :108:33]
  wire [7:0]  _biasedExp_T = {_unbiasedExp_T_1[6], _unbiasedExp_T_1} + 8'h7F;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:108:33, :109:31]
  wire        _GEN_3 = _msbIdx_T > 5'h6;	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:107:33, :111:26, :116:8]
  wire [94:0] _normalizedSig_T = {63'h0, io_in} << (_GEN_3 ? 6'h0 : {1'h0, 5'h7 - _msbIdx_T});	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:107:33, :111:26, :115:16, :116:{8,20}, :119:{18,36}, :124:27]
  wire [31:0] _normalizedSig_T_2 = io_in >> (_GEN_3 ? {1'h0, _msbIdx_T - 5'h7} : 6'h0);	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:107:33, :111:26, :114:17, :116:{8,20}, :117:{19,29}, :126:27]
  assign io_out = io_in == 32'h0 | $signed(_biasedExp_T) < 8'sh1 ? 16'h0 : {1'h0, _biasedExp_T, _msbIdx_T < 5'h7 ? _normalizedSig_T[6:0] : _normalizedSig_T_2[6:0]};	// @[generators/toyrocc/src/main/scala/BFloat16Ops.scala:88:7, :104:20, :107:33, :109:31, :111:26, :123:19, :124:{19,27,43}, :126:{19,27,44}, :129:22, :132:16, :133:{12,26}]
endmodule

